### ISSUE TITLE
Add an iterations marker and CLI option

### ISSUE THREAD

**Issue by lysnikolaou** [Quansight-Labs/pytest-run-parallel#8]
It'd be really helpful if we could add an `iterations` marker and CLI option, so that the tests can be rerun multiple times.

I can work on this.

**Comment by lysnikolaou** [comment]
@andfoy Can we do a release with this? I can take care of it if you want.

**Comment by andfoy** [comment]
Sure! I can do it in a few hours time, but if you want to go ahead, no problem at all!

**Comment by lysnikolaou** [comment]
Alright, let's make a decision on #12 first and I'll start the release process right after.
